### ISSUE TITLE
Studio - error when open a previously created proyect

### ISSUE THREAD

**Issue by paulcordova** [MikeGriffinReborn/EntitySpaces#34]
When I create a new proyect and add themplates, generated code and save the project
all works ok

BUT, when I open the previously created project file, I get this error
And I coludn't open the project file
and I must start from zero, :-(

I tested also with Studio version EntitySpacesStudio_20191.1218.0
and the error occurs too

thanks in advance

![image](https://user-images.githubusercontent.com/7750628/180264961-095ef1d0-a66d-4033-88b7-02a4112d54dd.png)

Error Message
Object reference not set to an instance of an object.

   at EntitySpaces.MetadataEngine.esSettings2010.SetDefaultSettings()
   at EntitySpaces.Common.esProject2010.Load(String fileNameAndFilePath, esSettings mainSettings)
   at EntitySpaces.Common.esProject.ConvertProject(String fileNameAndFilePath, esSettings settings)
   at EntitySpaces.Common.esProject.Load(String fileNameAndFilePath, esSettings mainSettings)
   at EntitySpaces.AddIn.ucProjects.OpenProject(String fileNameAndPath)

**Comment by mattphi** [comment]
Hi @paulcordova - I also noticed this and raised issue #17 and checked in a fix in my fork.  I'm unable to run it though, so I'm running ES2012 code generator for now
